[package]
name = "yew-bitcoin-qr"
version = "0.1.1"
edition = "2024"
license = "MIT"
description = "A simple QR code generator for the Yew framework"

[dependencies]
fast_qr = { version = "0.13.1", features = ["svg"] }
yew = { version = "0.21.0" }
web-sys = { version = "0.3", features = ["Navigator", "Clipboard"] }

[dev-dependencies]


